alias killruby='killall -9 ruby'
alias irb='irb --readline -r irb/completion'
alias bunbang='bundle install && !!'
alias bake='bundle exec rake'
alias be='bundle exec'
alias bi='bundle install'
alias be='bundle exec'
alias bu='bundle update'
