---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  name: bash_alias

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list:
    - recipe[minitest-handler]
    - recipe[bash_alias_test::setup]
    - recipe[bash_alias]
    - recipe[bash_alias_test::default]
  attributes:
    bash_alias:
      users:
        matt:
          l: ls -lha
          gst: git status
